### ISSUE TITLE
HUGE ISSUE

### ISSUE THREAD

**Issue by xxKevinSniperxx** [NWPlayer123/Cafiine-5.5.X#2]
when i open the cafiine_server.exe it just closes immediately

**Comment by CreeperMario** [comment]
This is a command line program. It is supposed to exit immediately, because you are supposed to be able to type commands after the program exits. But you can't do that unless the program is launched from a command prompt.

In the folder containing the server EXE file, hold SHIFT and right-click in an empty space, then click "Open Command Prompt Window here". Then type the name of the EXE file to run it.

**Comment by xxKevinSniperxx** [comment]
IT WORKED! Thank you dude
